In [1]:
import numpy as np
from typing import List, Dict, Union
from numpy.typing import NDArray



In [ ]:
VECTORES=np.array([[1,2,3],[3,4,5]])

for i in range(0,10000):
    VECTORES.np.append


In [4]:
def func(vector: NDArray[np.float64])->NDArray[np.float64]:
    
    return sum(vector)

In [6]:
np.apply_along_axis(func,axis=1,arr=VECTORES)

array([ 6, 12])

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.vstack([a, [5, 6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [2]:
def file_data_extraction(root: str)->List[NDArray[np.float64]]:

    file=open(root,"r")
    data=file.readlines()

    #data treatment
    data=[np.array((x.replace("\t","").replace("\n","")).split(" "),dtype=np.float64) for x in data if not (x[2]).isalpha()]

    return data 

def file_data_extraction2(root: str)->NDArray[np.float64]:

    file=open(root,"r")
    data=file.readlines()

    #data treatment
    data=np.array([(x.replace("\t","").replace("\n","")).split(" ") for x in data if not (x[2]).isalpha()],dtype=np.float64)

    return data 

In [9]:
root="./asia-cil.txt"
file_data_extraction2(root)

array([[ 53.003056, 172.660556],
       [ 53.003889, 172.669444],
       [ 53.004444, 172.679722],
       ...,
       [-54.750556, 158.85    ],
       [-54.751944, 158.840556],
       [-54.7525  , 158.836944]], shape=(924434, 2))

In [12]:
a[:,1]

array([2, 4])

In [25]:
def rot(vector: NDArray[np.float64],lat_0: np.float64, long_0: np.float64)->NDArray[np.float64]:

    factor=2*np.pi/360
    lat=vector[:,0]*factor
    long=vector[:,1]*factor
    lat_0=lat_0*factor
    long_0=long_0*factor

    a=np.sin(lat)*np.cos(lat_0)
    b=np.cos(lat)*np.cos(long-long_0)*np.sin(lat_0)
    y=np.cos(lat)*np.sin(long-long_0)


    new_lat=np.arcsin(a-b)/factor
    new_long=(long_0+np.atan2(y,a+b))/factor

    return np.stack((new_lat,new_long),axis=1)

In [26]:
rot(np.array([[30,90],[-30,270]]),30,90)

array([[  0.,  90.],
       [  0., 270.]])

In [58]:
#Spheric coortinates to Cartesian
def EtoC(vector: NDArray[np.float64])->NDArray[np.float64]:


    phi=vector[:,0]*2*np.pi/360
    lamb=vector[:,1]*2*np.pi/360

    X=np.cos(phi)*np.cos(lamb)
    Y=np.cos(phi)*np.sin(lamb)
    Z=np.sin(phi)

    return np.stack((X,Y,Z),axis=1)



def rot2(center:NDArray[np.float64])->NDArray[np.float64]:

    lat_0=center[0]
    long_0=center[1]


    temp_vector=EtoC(np.array([[0,long_0]]))


    rotation_vector=np.cross(np.array([0,0,1]),temp_vector)

    


    r1=rotation_vector[0][0]
    r2=rotation_vector[0][1]
    r3=rotation_vector[0][2]

    U=np.array([[0,-r3,r2],[r3,0,-r1],[-r2,r1,0]])

    R=np.cos(lat_0)*np.identity(3)+(1-np.cos(lat_0))*(rotation_vector*rotation_vector.T)+np.sin(lat_0)*U
    return R

def CtoE(vector: NDArray[np.float64])->NDArray[np.float64]:


    x=vector[:,0]
    y=vector[:,1]
    z=vector[:,2]

    phi=np.arcsin(z)
    lamb=np.atan2(y,x)

    return np.stack((phi,lamb),axis=1)

In [62]:
prueba=EtoC(np.array([[30,90]]))
rot2(np.array([30,90]))


(array([[ 1.00000000e+00, -5.17871627e-17, -6.04994883e-17],
        [-5.17871627e-17,  1.54251450e-01, -9.88031624e-01],
        [ 6.04994883e-17,  9.88031624e-01,  1.54251450e-01]]),
 array([[ 1.00000000e+00, -6.12323400e-17, -0.00000000e+00],
        [-6.12323400e-17,  3.74939946e-33,  0.00000000e+00],
        [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]))

array([[-0.64278761,  0.76604444,  0.        ]])

In [172]:
def EtoC(vector: NDArray[np.float64])->NDArray[np.float64]:


    phi=vector[:,0]
    lamb=vector[:,1]

    X=np.cos(phi)*np.cos(lamb)
    Y=np.cos(phi)*np.sin(lamb)
    Z=np.sin(phi)

    return np.stack((X,Y,Z),axis=1)

def CtoE(vector: NDArray[np.float64])->NDArray[np.float64]:


    x=vector[:,0]
    y=vector[:,1]
    z=vector[:,2]

    phi=np.arcsin(z)
    lamb=np.atan2(y,x)

    return np.stack((phi,lamb),axis=1)

def rot2(center:NDArray[np.float64])->NDArray[np.float64]:

    lat_0=center[0]
    long_0=center[1]

    temp_vector=EtoC(np.array([[0,long_0]]))
    rotation_vector=np.cross(np.array([0,0,1]),temp_vector)
    r1=rotation_vector[0][0]
    r2=rotation_vector[0][1]
    r3=rotation_vector[0][2]

    U=np.array([[0,-r3,r2],[r3,0,-r1],[-r2,r1,0]])
    #lat_0=-lat_0
    R=np.cos(lat_0)*np.identity(3)+(1-np.cos(lat_0))*(rotation_vector.T @ rotation_vector)+np.sin(lat_0)*U
    return R.T

In [177]:
phi=30*2*np.pi/360
lamb=120*2*np.pi/360
CtoE(EtoC(np.array([[phi,lamb]])) @ rot2(np.array([phi,lamb])).T)



119.97736230039438